# Generated by Django 5.1.5 on 2026-02-10 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_category_options_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='categoery',
            new_name='category',
        ),
    ]
